"""
Auto-Drafted Statutory Investigation Notice Generator for GuardChain
Generates standardized Cyber Crime Investigation / Exchange Compliance Notices (Draft templates)
modeled after Indian Law Enforcement protocols (Section 91 CrPC / Section 94 BNSS / FIU-IND).

IMPORTANT HONESTY NOTE:
This is a draft template generator for law enforcement officer review.
It is NOT connected to live government production gateways (NCRP, SAHYOG, CFCFRMS).
"""

from datetime import datetime, timezone


def generate_draft_notice(wallet_address, edges, freeze_info, chain="Ethereum"):
    """
    Generates a structured text template for an emergency Preservation & KYC requisition notice.
    """
    now = datetime.now(timezone.utc).strftime("%d-%b-%Y %H:%M:%S UTC")
    
    # Identify exchanges
    exchange_targets = []
    for e in edges:
        if isinstance(e, dict):
            if e.get("is_exchange", False):
                exchange_targets.append(e.get("to"))
        else:
            if len(e) >= 5 and e[4]:
                exchange_targets.append(e[1])
                
    unique_exchanges = list(set(exchange_targets))
    target_str = ", ".join(unique_exchanges) if unique_exchanges else "Intermediary Unhosted Wallets"
    urgency = freeze_info.get("level", "Moderate").upper()
    action_window = freeze_info.get("recommended_action_window", "Immediate")
    curr_unit = "USDT" if chain.lower() == "tron" else "ETH"
    
    total_val = sum([e.get("value_eth", e.get("value", 0.0)) if isinstance(e, dict) else e[2] for e in edges])

    notice_text = f"""================================================================================
          DRAFT STATUTORY PRESERVATION & REQUISITION NOTICE
          [FOR INVESTIGATING OFFICER (I.O.) REVIEW & ISSUANCE ONLY]
   ** PROTOTYPE TEMPLATE — NOT LINKED TO LIVE GOVERNMENT GATEWAYS **
================================================================================

DATE OF NOTICE: {now}
INVESTIGATION REF NO: GC-CYBER-{wallet_address[:8].upper()}-{datetime.now().strftime('%Y%m%d')}
SUBJECT: EMERGENCY REQUISITION FOR WALLET PRESERVATION & KYC DATA UNDER 
         SECTION 91 Cr.P.C. / SECTION 94 BNSS (BHARATIYA NAGARIK SURAKSHA SANHITA)

TO:
  The Nodal Officer / Compliance Department,
  Designated Virtual Asset Service Provider (VASP) / Exchange Desk
  Target Identifier(s): {target_str}

URGENCY LEVEL: [{urgency}]
RECOMMENDED FREEZE WINDOW: {action_window}

1. PARTICULARS OF TRACED INCIDENT:
   - Primary Suspect Wallet: {wallet_address}
   - Blockchain Network: {chain.upper()} (Mainnet)
   - Total Tracked Volume: {total_val:.4f} {curr_unit}
   - Detected Off-ramp Destination: {target_str}

2. FORENSIC INTELLIGENCE SUMMARY:
   {freeze_info.get('reason', 'Laundering trail detected routing funds toward centralized exchange nodes.')}

3. REQUISITION FOR IMMEDIATE ACTION:
   Pursuant to the powers vested in the Cyber Crime Investigation Division, you are hereby requested to:
   a) Freeze / Place on debit freeze all accounts, wallets, and sub-accounts associated with the target address(es).
   b) Furnish complete KYC / CDD records of the account holder:
      - Full Registered Name & Date of Birth
      - Government ID Proofs (Aadhaar / PAN / Passport)
      - Registered Mobile Number & Email Address
      - IP Logs with Timestamp & Port numbers for all logins within 30 days
      - Linked Bank Account / UPI VPA / Off-ramp withdrawal destinations
   c) Provide complete transaction ledger / internal transfer records relating to the aforementioned crypto hashes.

4. COMPLIANCE TIMELINE:
   In view of the high risk of asset dissipation (Freeze Window: {action_window}),
   acknowledgment and provisional compliance is requested within 6 hours of receipt.

--------------------------------------------------------------------------------
INVESTIGATING OFFICER (I.O.) SIGNATURE / SEAL:

Name: _______________________________
Rank/Designation: ___________________
Police Station / Cyber Cell: _________
State/Agency: ________________________
--------------------------------------------------------------------------------
* DISCLAIMER: This draft notice is auto-generated by the GuardChain Forensic Engine as a 
  decision-support tool for law enforcement. Formal verification by the investigating officer is required.
"""
    return {
        "title": f"Draft Statutory Requisition Notice - {wallet_address[:10]}",
        "notice_text": notice_text,
        "is_draft": True,
        "generated_at": now,
        "target_exchanges": unique_exchanges,
        "urgency_level": urgency
    }
