"""
PDF Investigation Report Generator for GuardChain
Uses fpdf2 (free, open source) to generate publication-grade forensic reports
for law enforcement officers and cyber crime investigators.
"""

from datetime import datetime, timezone
from fpdf import FPDF


class GuardChainPDFReport(FPDF):
    def __init__(self, wallet_address, chain="Ethereum"):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.wallet_address = wallet_address
        self.chain = chain
        self.set_auto_page_break(auto=True, margin=18)

    def header(self):
        # Top banner
        self.set_fill_color(15, 23, 42)  # Slate 900
        self.rect(0, 0, 210, 18, "F")
        
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(56, 189, 248)  # Cyan 400
        self.set_xy(10, 5)
        self.cell(100, 8, "GUARDCHAIN // BLOCKCHAIN FORENSIC INTELLIGENCE", align="L")
        
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(248, 113, 113)  # Red 400
        self.set_xy(110, 5)
        self.cell(90, 8, "RESTRICTED // LAW ENFORCEMENT & FORENSIC USE ONLY", align="R")
        self.ln(15)

    def footer(self):
        self.set_y(-16)
        self.set_draw_color(226, 232, 240)
        self.line(10, 281, 200, 281)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(100, 116, 139)
        disclaimer = "DISCLAIMER: Generated by GuardChain Forensic Engine. Serves as investigative intelligence. Requires officer verification before judicial filing."
        self.cell(150, 8, disclaimer, align="L")
        self.cell(40, 8, f"Page {self.page_no()}/{{nb}}", align="R")


def generate_pdf_report(wallet_address, edges, freeze_info, chain="Ethereum", cycle_info=None, anomaly_info=None):
    """
    Builds a complete forensic dossier PDF in memory and returns raw bytes.
    """
    pdf = GuardChainPDFReport(wallet_address, chain)
    pdf.alias_nb_pages()
    pdf.add_page()

    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    # Title Section
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "Cryptocurrency Trace & Asset Recovery Report", ln=True)
    
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, f"Case Generated: {now_utc} | Target Network: {chain.upper()}", ln=True)
    pdf.ln(3)

    # 1. Target Wallet & Overview Card
    pdf.set_fill_color(241, 245, 249)
    pdf.set_draw_color(203, 213, 225)
    pdf.rect(10, pdf.get_y(), 190, 26, "DF")

    y_start = pdf.get_y() + 3
    pdf.set_xy(14, y_start)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(40, 5, "TARGET WALLET:")
    pdf.set_font("Courier", "B", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(130, 5, wallet_address, ln=True)

    pdf.set_xy(14, y_start + 6)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(40, 5, "CHAIN / NETWORK:")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(50, 5, f"{chain} (Mainnet)")
    
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(40, 5, "TOTAL TRACED HOPS:")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    max_hop = max([e.get("hop", 1) if isinstance(e, dict) else e[3] for e in edges], default=0)
    pdf.cell(40, 5, f"{max_hop} Levels ({len(edges)} paths)", ln=True)

    pdf.set_xy(14, y_start + 12)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(40, 5, "TOTAL VALUE TRACED:")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(2, 132, 199)
    total_val = sum([e.get("value_eth", e.get("value", 0.0)) if isinstance(e, dict) else e[2] for e in edges])
    curr_unit = "USDT" if chain.lower() == "tron" else "ETH"
    pdf.cell(50, 5, f"{total_val:.4f} {curr_unit}")

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(40, 5, "EXCHANGE EXITS:")
    pdf.set_font("Helvetica", "B", 9)
    exchanges_count = len([e for e in edges if (e.get("is_exchange", False) if isinstance(e, dict) else e[4])])
    if exchanges_count > 0:
        pdf.set_text_color(220, 38, 38)
    else:
        pdf.set_text_color(22, 163, 74)
    pdf.cell(40, 5, f"{exchanges_count} Detected", ln=True)

    pdf.set_y(y_start + 25)

    # 2. Freeze Window & Urgency Analysis Box
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 8, "1. Freeze Window & Action Urgency Analysis", ln=True)

    # Urgency Box background color based on score
    score = freeze_info.get("score", 0)
    level = freeze_info.get("level", "Low/Unknown")
    
    if level == "Critical":
        box_bg = (254, 242, 242)
        box_border = (239, 68, 68)
        badge_bg = (220, 38, 38)
    elif level == "High":
        box_bg = (255, 247, 237)
        box_border = (249, 115, 22)
        badge_bg = (234, 88, 12)
    elif level == "Moderate":
        box_bg = (254, 252, 232)
        box_border = (234, 179, 8)
        badge_bg = (202, 138, 4)
    else:
        box_bg = (240, 253, 244)
        box_border = (34, 197, 94)
        badge_bg = (22, 163, 74)

    pdf.set_fill_color(*box_bg)
    pdf.set_draw_color(*box_border)
    pdf.rect(10, pdf.get_y(), 190, 28, "DF")

    card_y = pdf.get_y() + 3
    pdf.set_xy(14, card_y)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*badge_bg)
    pdf.cell(90, 6, f"SCORE: {score}/100 - [{level.upper()}]")
    
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.set_xy(110, card_y)
    pdf.cell(85, 6, f"Action Window: {freeze_info.get('recommended_action_window', 'N/A')}", align="R")

    pdf.set_xy(14, card_y + 7)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(51, 65, 85)
    reason_txt = freeze_info.get("reason", "No specific intelligence reasoning available.")
    pdf.multi_cell(182, 4.2, reason_txt)

    pdf.set_y(card_y + 27)

    # 3. Anomaly & Laundering Pattern Summary
    if cycle_info or anomaly_info:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 8, "2. Laundering Pattern & Statistical Anomaly Summary", ln=True)

        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(30, 41, 59)
        
        cycle_detected = cycle_info.get("circular_pattern_detected", False) if cycle_info else False
        anomaly_score = anomaly_info.get("anomaly_score", 0) if anomaly_info else 0
        
        c_status = "WARNING: Circular fund cycle detected (funds returned to prior wallet node)" if cycle_detected else "No circular fund cycling detected in direct trace path."
        pdf.cell(0, 5, f"- Pattern Cycling: {c_status}", ln=True)
        pdf.cell(0, 5, f"- Statistical Anomaly Rating: {anomaly_score}/100 ({anomaly_info.get('verdict', 'Normal') if anomaly_info else 'Standard'})", ln=True)
        pdf.ln(2)

    # 4. Traced Transaction Ledger Table
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 8, "3. Traced Transaction Ledger (Hop-by-Hop)", ln=True)

    # Table Header
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    
    col_w = [14, 52, 52, 36, 36]
    pdf.cell(col_w[0], 7, "Hop", 1, 0, "C", fill=True)
    pdf.cell(col_w[1], 7, "Sender (From)", 1, 0, "C", fill=True)
    pdf.cell(col_w[2], 7, "Receiver (To)", 1, 0, "C", fill=True)
    pdf.cell(col_w[3], 7, f"Value ({curr_unit})", 1, 0, "C", fill=True)
    pdf.cell(col_w[4], 7, "Classification", 1, 1, "C", fill=True)

    # Rows
    pdf.set_font("Courier", "", 7.5)
    row_alt = False
    for item in edges:
        if isinstance(item, dict):
            f_addr = item.get("from", "")
            t_addr = item.get("to", "")
            val = item.get("value_eth", item.get("value", 0.0))
            h = item.get("hop", 1)
            is_exc = item.get("is_exchange", False)
            exc_label = item.get("exchange_label", "Exchange") if is_exc else "Private Wallet"
        else:
            f_addr = item[0]
            t_addr = item[1]
            val = item[2]
            h = item[3]
            is_exc = item[4]
            exc_label = item[5] if len(item) > 5 and item[5] else ("Exchange" if is_exc else "Private Wallet")

        if is_exc:
            pdf.set_fill_color(254, 226, 226)
            pdf.set_text_color(185, 28, 28)
        elif row_alt:
            pdf.set_fill_color(248, 250, 252)
            pdf.set_text_color(15, 23, 42)
        else:
            pdf.set_fill_color(255, 255, 255)
            pdf.set_text_color(15, 23, 42)

        pdf.cell(col_w[0], 6, str(h), 1, 0, "C", fill=True)
        pdf.cell(col_w[1], 6, f"{f_addr[:8]}...{f_addr[-6:]}", 1, 0, "C", fill=True)
        pdf.cell(col_w[2], 6, f"{t_addr[:8]}...{t_addr[-6:]}", 1, 0, "C", fill=True)
        pdf.set_font("Helvetica", "B" if is_exc else "", 7.5)
        pdf.cell(col_w[3], 6, f"{val:.4f}", 1, 0, "R", fill=True)
        pdf.cell(col_w[4], 6, exc_label, 1, 1, "C", fill=True)
        pdf.set_font("Courier", "", 7.5)
        row_alt = not row_alt

    pdf.ln(5)

    # 5. Law Enforcement Action / Draft Notice Template Guidance
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 6, "4. Law Enforcement Regulatory & Exchange Compliance Protocol", ln=True)
    
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(71, 85, 105)
    protocol_text = (
        "Pursuant to standard financial intelligence protocols (e.g., Section 91 CrPC / Section 94 BNSS / FIU-IND Guidelines):\n"
        "1. If destination is flagged as an Exchange, issue an immediate emergency Preservation & Freeze Request to the compliance desk.\n"
        "2. Request KYC records: Full Name, National ID, linked Bank Account/UPI, IP login history, and deposit TX hash.\n"
        "3. Lodge corresponding cyber incident reference with designated nodal coordination agencies."
    )
    pdf.multi_cell(190, 4, protocol_text)

    # Output as bytearray
    return bytes(pdf.output())
